### PR TITLE
Added classes for WMS backends

### PR DESCRIPTION
**Pull request by cippino**
Hi all,
I cloned Coverage store classes to get WMS stores. At this moment is available only on reader.

Cheers.

### CODE REVIEW

**Comment by mbarto** [comment]
Hi Federico, do you think you can add some unit tests?

**Comment by cippino** [comment]
Yes I can clone feature/coverage unit tests, if you need.

**Comment by mbarto** [comment]
It would help, thanks

**Comment by cippino** [comment]
Sorry for long waiting. I hope this can be enought.

**Comment by mbarto** [comment]
Thanks for the contribution

**Pull request merged**
