### PR TITLE
Publish a WorldImage already in a filesystem readable by GeoServer.

### PR DESCRIPTION
**Pull request by marcopollivier**
Publish a WorldImage already in a filesystem readable by GeoServer.

### CODE REVIEW

**Comment by simboss** [comment]
Probably beating a dead horse but we need unit tests in order to move with this PR.

**Comment by marcopollivier** [comment]
Sorry. I'll do that.

**Comment by simboss** [comment]
thx

**Comment by marcopollivier** [comment]
Here are the tests

**Comment by simboss** [comment]
Thx for this, I'll ping the devs to review this shortly.

**Comment by marcopollivier** [comment]
Hi, @simboss. This PR needs any changes yet?

**Pull request closed without merging**
